// <auto-generated />
using System;
using EventPulse.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventPulse.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301220107_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventPulse.Core.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Harika bir etkinlik, kesinlikle orada olacağım!",
                            CreatedAt = new DateTime(2026, 3, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            EventId = 1,
                            UserId = "test_user_1"
                        });
                });

            modelBuilder.Entity("EventPulse.Core.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Events", t =>
                        {
                            t.HasCheckConstraint("CK_Event_MaxCapacity", "\"MaxCapacity\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Teknoloji",
                            City = "İstanbul",
                            Description = ".NET 8 ve Flutter ile modern uygulama geliştirme pratikleri.",
                            MaxCapacity = 200,
                            StartDate = new DateTime(2026, 5, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Yazılım Mimari Zirvesi"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Müzik",
                            City = "İzmir",
                            Description = "Sevilen rock gruplarıyla yaza merhaba diyoruz.",
                            MaxCapacity = 5000,
                            StartDate = new DateTime(2026, 6, 20, 19, 30, 0, 0, DateTimeKind.Utc),
                            Title = "Açık Hava Rock Konseri"
                        });
                });

            modelBuilder.Entity("EventPulse.Core.Entities.UserAttendance", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AttendedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("UserAttendances");
                });

            modelBuilder.Entity("EventPulse.Core.Entities.Comment", b =>
                {
                    b.HasOne("EventPulse.Core.Entities.Event", "Event")
                        .WithMany("Comments")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventPulse.Core.Entities.UserAttendance", b =>
                {
                    b.HasOne("EventPulse.Core.Entities.Event", "Event")
                        .WithMany("Attendances")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventPulse.Core.Entities.Event", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
